name: Publish to npmjs

on:
  release:
    types: [created]  # Se ejecutará cuando hagas un release en GitHub

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org/'
          
      - name: Set package path
        run: |
          repo_name=${GITHUB_REPOSITORY##*/}
          repo_lower=$(echo "$repo_name" | tr '[:upper:]' '[:lower:]')
          echo "PACKAGE_DIR=Packages/com.jaimecamacho.$repo_lower" >> $GITHUB_ENV

      - name: Sync README
        run: cp README.md "$PACKAGE_DIR/README.md"

      - name: Publish package
        run: npm publish
        working-directory: $PACKAGE_DIR
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
